---
title: "Assignment 5"
author: "Kyle See"
date: "4/12/2022"
output: html_document
---

>>Apply hierarchical clustering to the data using Euclidean distance to the normalized
measurements. Use Agnes to compare the clustering from  single linkage, complete
linkage, average linkage, and Ward. Choose the best method.

> Starting off, we omit NA's and set the working directory. 

rm(list=ls())
setwd("/Users/kyle/Downloads")
getwd()
cereals = read.csv("Cereals.csv")
is.na(cereals)
complete.cases(cereals)
cereals[complete.cases(cereals),]

library(lattice)
library(grid)

sum(is.na(cereals))
cereals1 = na.omit(cereals)

cor.test(x=as.integer(factor(cereals1$mfr)), y=as.integer(factor(cereals1$type)), method = "pearson")

rownames(cereals1) <- cereals1$name
cereals1$name = NULL
scale = function(cereals1){
  return((cereals1-min(cereals1,na.rm = TRUE)))/(max(cereals1, na.rm = TRUE)) - min(cereals1, na.rm = TRUE)
}

scaled.dat <- scale(cereals[,4:16])
scaled.dat1= na.omit(scaled.dat)

dist <- dist(scaled.dat1, method = "euclidean")
hc_fit <- hclust(dist, method = "ward.D2")
plot(hc_fit)

points_hc <- cutree(hc_fit, k = 6)
cereals_clusts_hc <- cbind(points_hc, scaled.dat1)

hc_complete <- hclust(dist, method = "complete")
plot(hc_complete)

hc_single <- hclust(dist, method = "single")
plot(hc_single)

hc_average <- hclust(dist, method = "average")
plot(hc_average)


> The method that I would chose would likely be single clustering. 

>>How many clusters would you choose?

>Based off of the dendograms that are plotted, I would choose two methods, single and average clustering. When we review the dendograms that are created based off of these methods, we can see that single clustering far and away has the lowest height on the Y axis, where as average is the second highest. This is indicative of the level of variance between points, where as a higher Y axis or "height" means there is a higher variance. 

>>The elementary public schools would like to choose a set of cereals to include in their 
daily cafeterias. Every day a different cereal is offered, but all cereals should support a 
healthy diet. For this goal, you are requested to find a cluster of “healthy cereals.” 

>For this question, we will use do a principle component analysis. 

pca <- prcomp(na.omit(scaled.dat1[,-c(1:3)]), scale. = T)
summary(pca)
pca$rotation[, 1:5]

library(ggplot2)

pca1 <- prcomp(t(scaled.dat1), scale = TRUE)

plot(pca1$x[,1], pca$x[,2])

> Through the plotting of the different cereals based on principle component analysis, we can see that the top 5 cereals that should be chosen for a different cereal each day are, in the following order: All-Bran with Extra Fiber, 100% Bran, Shredded Wheat 'n' Bran, Bran Flakes, and Shredded Wheat spoon size. 






